    services:
      api:
        image: ghcr.io/ervinhun/devops-exam-project-ervinhun-api:staging
        container_name: todowithextras-api
        ports:
          - "5000:5000"

      client:
        image: ghcr.io/ervinhun/devops-exam-project-ervinhun-client:staging
        container_name: dowa-client
        ports:
          - "80:80"
        depends_on:
          - api

    networks:
      default:
        name: dowa-network