    services:
      api:
        image: ghcr.io/tboulund-devops/devops-exam-project-ervinhun-api:${VERSION}
        env_file:
          - .env
        container_name: todowithextras-api
        ports:
          - "5000:8080"

      client:
        image: ghcr.io/tboulund-devops/devops-exam-project-ervinhun-client:${VERSION}
        env_file:
          - .env
        container_name: dowa-client
        ports:
          - "3000:5173"
        depends_on:
          - api

    networks:
      default:
        name: dowa-network